### ISSUE TITLE
GitHub Actions RubyGems Push Fails with MFA-Enabled Account

### ISSUE THREAD

**Issue by snowwshiro** [snowwshiro/stomp_base#19]
# GitHub Actions RubyGems Push Fails with MFA-Enabled Account

## Problem Description

The current GitHub Actions release workflow fails when attempting to push gems to RubyGems.org for accounts that have Multi-Factor Authentication (MFA) enabled. When MFA is enabled on your RubyGems account, traditional API key authentication fails in automated workflows because it cannot provide the required one-time password (OTP).

## Current Workflow Issue

The release workflow in `.github/workflows/release.yml` currently uses:

```yaml
- name: Publish to RubyGems
  run: |
    mkdir -p ~/.gem
    echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > ~/.gem/credentials
    chmod 0600 ~/.gem/credentials
    gem push *.gem
  env:
    RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
```

## Error Symptoms

- Gem push fails with authentication errors
- MFA-enabled RubyGems accounts cannot authenticate using API key alone
- Release workflow completes successfully until the RubyGems push step

## Proposed Solution: Trusted Publishing with OIDC

RubyGems.org supports OpenID Connect (OIDC) trusted publishing, which eliminates the need for API keys and automatically handles MFA requirements.

### Benefits of Trusted Publishing

- **No API keys to manage** - Uses secure OIDC tokens
- **MFA compatible** - Works seamlessly with MFA-enabled accounts
- **Enhanced security** - Short-lived, scoped authentication tokens
- **Audit trail** - Clear connection between GitHub Actions and RubyGems

### 1. Configure Trusted Publishing on RubyGems.org

1. **Login to RubyGems.org** with your MFA-enabled account
2. **Navigate to your gem** (e.g., `https://rubygems.org/gems/stomp_base`)
3. **Go to "Trusted publishing"** in the gem management section
4. **Add a new trusted publisher** with these settings:
   - **Repository owner**: `snowwshiro` (your GitHub username/organization)
   - **Repository name**: `stomp_base` (your repository name)
   - **Workflow filename**: `release.yml` (your workflow file name)
   - **Environment name**: (leave blank if not using deployment environments)

### 2. Update GitHub Actions Workflow

Replace the current RubyGems push step with:

```yaml
- name: Publish to RubyGems
  uses: rubygems/release-gem@v1
  with:
    working-directory: ./
```

Complete workflow example:

```yaml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # Required for OIDC
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    
    - name: Build gem
      run: gem build stomp_base.gemspec
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.gem"
        generate_release_notes: true
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to RubyGems
      uses: rubygems/release-gem@v1
      with:
        working-directory: ./
```

#### Required Permissions
```yaml
permissions:
  contents: write      # For creating GitHub releases
  id-token: write      # For OIDC authentication with RubyGems
```

#### Workflow Triggers
```yaml
on:
  push:
    tags:
      - 'v*'        # Triggers on tags like v1.0.0, v2.1.3, etc.
```

### 4. Release Process

To trigger a release after implementation:

```bash
# 1. Update version in your version.rb file
# 2. Commit the version change
git add lib/stomp_base/version.rb
git commit -m "Bump version to 1.0.0"

# 3. Create and push the tag
git tag v1.0.0
git push origin v1.0.0

# 4. GitHub Actions will automatically:
#    - Run tests
#    - Build the gem
#    - Create GitHub release
#    - Publish to RubyGems.org
```

### Before (API Key Method)
```yaml
- name: Publish to RubyGems
  run: |
    mkdir -p ~/.gem
    echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > ~/.gem/credentials
    chmod 0600 ~/.gem/credentials
    gem push *.gem
  env:
    RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
```

### After (Trusted Publishing)
```yaml
- name: Publish to RubyGems
  uses: rubygems/release-gem@v1
  with:
    working-directory: ./
```

#### 1. "Authentication failed" Error
- **Check**: Trusted publishing configuration on RubyGems.org
- **Verify**: Repository owner/name matches exactly
- **Ensure**: Workflow name matches the configured name

#### 2. "Permission denied" Error
- **Check**: `id-token: write` permission is set
- **Verify**: Repository has the correct permissions

#### 3. "Workflow not found" Error
- **Check**: Workflow filename matches trusted publishing configuration
- **Verify**: Workflow is in the default branch

### Debugging Steps

1. **Check workflow logs** in GitHub Actions for detailed error messages
2. **Verify trusted publishing configuration** on RubyGems.org
3. **Test with a development gem** first if possible
4. **Check GitHub repository settings** for any restrictions

## Security Considerations

- **Repository security**: Ensure your repository is properly secured
- **Branch protection**: Consider protecting your main branch
- **Review permissions**: Regularly audit trusted publishing configurations
- **Monitor releases**: Set up notifications for successful/failed releases

## Expected Outcome

After implementing trusted publishing:
- GitHub Actions can successfully push gems to RubyGems.org
- No manual API key management required
- MFA requirements are automatically satisfied
- More secure and maintainable release process

## Priority

**High** - This issue blocks the automated release process for MFA-enabled RubyGems accounts, requiring manual intervention for each release.

## References

- [RubyGems Trusted Publishing Documentation](https://guides.rubygems.org/trusted-publishing/)
- [GitHub Actions OIDC Documentation](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect)
- [RubyGems Release Action](https://github.com/rubygems/release-gem)
- [RubyGems MFA Documentation](https://guides.rubygems.org/setting-up-multifactor-authentication/)
- [GitHub Actions Workflow Syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions)
